"""Add verification status and other user fields

Revision ID: d8ce15859554
Revises: a1b2c3d4e5f6
Create Date: 2026-06-02 23:24:56.499945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""Add verification status and other user fields

Revision ID: d8ce15859554
Revises: a1b2c3d4e5f6
Create Date: 2026-06-02 23:24:56.499945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8ce15859554'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('code_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'code_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'verification_status')
    # ### end Alembic commands ###
